NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 240 --was 50
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 240 --was 50
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36 --was 36

NDefines.NDiplomacy.DIPLOMACY_REQUEST_EXPIRY_DAYS = 7 --was 30
NDefines.NDiplomacy.TRUCE_PERIOD_AFTER_KICKING_FROM_FACTION = 0 --was 0
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_KICKING_NEW_MEMBERS_OF_FACTION = 0 --was 0
NDefines.NDiplomacy.NUM_DAYS_TO_ENABLE_REINVITE_KICKED_NATIONS = 0 --was 90
NDefines.NDiplomacy.BASE_STAGE_COUP_DAILY_PP = 999 --was 999
NDefines.NDiplomacy.BASE_STAGE_COUP_TOTAL_COST = 0 --was 0
NDefines.NDiplomacy.DIPLOMACY_HOURS_BETWEEN_REQUESTS = 8 --was 24
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 1 --was 1
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 2 --was 1
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 0 --was 1
NDefines.NDiplomacy.BASE_CONDITIONAL_PEACE_WARESCORE_RATIO = 0.0 --was 0.5
NDefines.NDiplomacy.BASE_CONDITIONAL_PEACE_MONTHS = 0 --was 6
NDefines.NDiplomacy.PEACE_SCORE_PER_PASS = 2.0 --was 0.2
NDefines.NDiplomacy.NOT_READY_FOR_WAR_BASE = 0 --was -50
NDefines.NDiplomacy.FRONT_IS_DANGEROUS = 0 --was -100
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_ANNEX = 10 --was 300
NDefines.NDiplomacy.AUTONOMY_LEVEL_CHANGE_PP_FREE = 10 --was 300
NDefines.NDiplomacy.ASSUME_FACTION_LEADERSHIP_PP_COST = 2000 --was 200

NDefines.NCountry.VP_TO_SUPPLY_BASE = 2 --was 1
NDefines.NCountry.SUPPLY_PATH_MAX_DISTANCE = 8 --was 15
NDefines.NCountry.REINFORCEMENT_EQUIPMENT_DELIVERY_SPEED = 3.0 --was 3.0
NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 100.0 --was 10.0
NDefines.NCountry.MIN_MANPOWER_RATIO = 0.25 --was 0.15
NDefines.NCountry.BASE_MOBILIZATION_SPEED = 0.03 --was 0.01
NDefines.NCountry.INTERCEPTION_WAR_SUPPORT_SCALE = 0.00004 --was 0.00001
NDefines.NCountry.NUM_DAYS_TO_FULLY_DELETE_STOCKPILED_EQUIPMENT = 3650 --was 9999
NDefines.NCountry.AIR_SUPPLY_CONVERSION_SCALE = 0.35 --was 0.05
NDefines.NCountry.STARTING_COMMAND_POWER = 50.0 --was 0.0
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 250.0 --was 100.0
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.15 --was 0.15
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 84 --was 60
NDefines.NCountry.PARADROP_AIR_SUPERIORITY_RATIO = 0.9 --was 0.7

NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 20 --was 5
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 20 -- was 10
NDefines.NProduction.ANNEX_FIELD_EQUIPMENT_RATIO = 1.0 --was 0.25
NDefines.NProduction.ANNEX_FUEL_RATIO = 1.0 --was 0.25
NDefines.NProduction.ANNEX_CONVOYS_RATIO = 1.0 --was 0.25
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 1000000 --was 999999
NDefines.NProduction.MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 0.9 --was 0.75
NDefines.NProduction.MIN_LICENSE_ACTIVE_DAYS = 0 --was 30
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0.0 --was 0.0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0.0 --was 0.0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0.0 --was 0.0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0.0 --was 0.0
NDefines.NProduction.MIN_NAVAL_EQUIPMENT_CONVERSION_IC_COST_FACTOR = 0.0 --was 0.0
NDefines.NProduction.SHIP_REFIT_MAX_PROGRESS_TO_CANCEL = 1.0 --was 0.2

NDefines.NDeployment.BASE_DEPLOYMENT_TRAINING = 2 --was 2

NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 45.0 --was 45.0

NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 15 --was 15

NDefines.NPolitics.DEFAULT_OCCUPATION_POLICY = 1 --was 1
NDefines.NPolitics.NUM_OCCUPATION_POLICIES = 1 --was 1

NDefines.NBuildings.INFRA_TO_SUPPLY = 3 --was 2.5
NDefines.NBuildings.MAX_SHARED_SLOTS = 99 --was 99

NDefines.NMilitary.HOURLY_ORG_MOVEMENT_IMPACT = -0.15 --was -0.2
NDefines.NMilitary.ZERO_ORG_MOVEMENT_MODIFIER = -0.6 --was -0.8
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 0 --was 999
NDefines.NMilitary.RECON_SKILL_IMPACT = 8 --was 5
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0 --was 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0 --was 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0 --was 0
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 2000 --was 999
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 2000 --was 999
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 2000 --was 999
NDefines.NMilitary.COMBAT_MINIMUM_TIME = 2 --was 4
NDefines.NMilitary.TACTIC_SWAP_FREQUENCEY = 4 --was 24
NDefines.NMilitary.RIVER_CROSSING_PENALTY = -0.2 --was -0.15
NDefines.NMilitary.RIVER_CROSSING_PENALTY_LARGE = -0.3 --was -0.3
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_IMPACT = -0.40 --was -0.40
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE = 0.65	-- more AA attack will approach this amount of help (diminishing returns)
NDefines.NMilitary.ENEMY_AIR_SUPERIORITY_DEFENSE_STEEPNESS = 224 -- how quickly defense approaches the max impact diminishing returns curve
NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 2 --was 2
NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 156.0 --was 62.0
NDefines.NMilitary.UNIT_EXP_LEVELS = { 0.2, 0.3, 0.4, 0.5 } --was vanilla
NDefines.NMilitary.SLOWEST_SPEED = 4 --was 4
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.15 --was 0.15
NDefines.NMilitary.EXPERIENCE_LOSS_FACTOR = 0.00 --was 0.00
NDefines.NMilitary.EQUIPMENT_COMBAT_LOSS_FACTOR = 0.5 --was 0.7
NDefines.NMilitary.TRAINING_ATTRITION = 0.00 --was 0.015
NDefines.NMilitary.OVERSEAS_LOSE_EQUIPMENT_FACTOR = 1.0 --was 1.0
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.0 --was 0.0
NDefines.NMilitary.ORG_LOSS_FACTOR_ON_CONQUER = 0.25 --was 0.2
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.01 --was 0.02
NDefines.NMilitary.ACCLIMATIZATION_IN_COMBAT_SPEED_FACTOR = 1 --was 3
NDefines.NMilitary.ACCLIMATIZATION_SPEED_GAIN = 0.015 --was 0.15
NDefines.NMilitary.ACCLIMATIZATION_LOSS_SPEED_FACTOR = 4.0 --was 2.0
NDefines.NMilitary.PROMOTE_LEADER_CP_COST = 15.0 --was 30.0
NDefines.NMilitary.XP_GAIN_PER_OVERRUN_UNIT = 0.0 --was 35.0
NDefines.NMilitary.XP_GAIN_FOR_SHATTERING = 0.0 --was 35.0
NDefines.NMilitary.ARMY_TRAINING_FUEL_MULT = 0.2 --was 1.0
NDefines.NMilitary.ARMY_LEADER_XP_GAIN_PER_UNIT_IN_COMBAT = 0.0 --was 0.0
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.0 --was 0.0
NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.0000 --was 0.0000

NDefines.NAir.AIR_WING_MAX_SIZE = 6400 --was 1600
NDefines.NAir.COMBAT_MULTIPLANE_CAP = 2 --was 2
NDefines.NAir.ANTI_AIR_ATTACK_TO_DAMAGE_REDUCTION_FACTOR = 2.0 --was 2.0
NDefines.NAir.ANTI_AIR_MAXIMUM_DAMAGE_REDUCTION_FACTOR = 0.65 --was 0.65
NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.000 --was 0.000
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0 --was 0
NDefines.NAir.NAVAL_COMBAT_EXTERNAL_PLANES_JOIN_RATIO = 0.10 --was 0.10
NDefines.NAir.NAVAL_STRIKE_TARGETTING_TO_AMOUNT = 0.5 --was 0.5
NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_STR = 1.5 --was 1.5
NDefines.NAir.NAVAL_STRIKE_DAMAGE_TO_ORG = 2.25 --was 2.25
NDefines.NAir.AIR_MORE_GROUND_CREWS_COST = 500.0 --was 999.0
NDefines.NAir.ANTI_AIR_PLANE_DAMAGE_FACTOR = 0.5 --was 0.5
NDefines.NAir.ACCIDENT_CHANCE_BASE = 0.02 --was 0.05
NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0.9 --was 0.75
NDefines.NAir.ACE_WING_SIZE_MAX_BONUS = 1 --was 10
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_TACTICAL_BOMBER = 0.1 --was 0.192
NDefines.NAir.EFFICIENCY_REGION_CHANGE_DAILY_GAIN_STRATEGIC_BOMBER = 0.018 --was 0.072
NDefines.NAir.AIR_WING_XP_LOSS_WHEN_KILLED = 0 --was 300
NDefines.NAir.DISRUPTION_FACTOR = 5.0 --was 4.0
NDefines.NAir.ESCORT_FACTOR = 2.5 --was 2.0
NDefines.NAir.AIR_NAVAL_KAMIKAZE_DAMAGE_MULT = 40.0 -- Balancing value to increase usual damage to Strength for Kamikaze
NDefines.NAir.AIR_NAVAL_KAMIKAZE_LOSSES_MULT = 1.0  -- Balancing value to increase usual losses if Kamikaze participating in the battle
NDefines.NAir.MISSION_COMMAND_POWER_COSTS = {  -- command power cost per plane to create a mission
		0.0, -- AIR_SUPERIORITY
		0.0, -- CAS		
		0.0, -- INTERCEPTION	
		0.0, -- STRATEGIC_BOMBER
		0.0, -- NAVAL_BOMBER	
		0.0, -- DROP_NUKE		
		0.0, -- PARADROP		
		0.0, -- NAVAL_KAMIKAZE	
        0.0, -- PORT_STRIKE		
		0.0, -- AIR_SUPPLY		
		0.0, -- TRAINING
		0.0, -- NAVAL_MINES_PLANTING
		0.0, -- NAVAL_MINES_SWEEPING
	}
NDefines.NAir.MISSION_FUEL_COSTS = {  -- fuel cost per plane for each mission
		1.0, -- AIR_SUPERIORITY
		1.0, -- CAS		
		1.0, -- INTERCEPTION	
		1.0, -- STRATEGIC_BOMBER
		1.0, -- NAVAL_BOMBER	
		1.0, -- DROP_NUKE		
		1.0, -- PARADROP		
		1.0, -- NAVAL_KAMIKAZE	
		1.0, -- PORT_STRIKE		
		1.0, -- AIR_SUPPLY		
		0.2, -- TRAINING
		1.0, -- NAVAL_MINES_PLANTING
		1.0, -- NAVAL_MINES_SWEEPING
	}

NDefines.NNavy.ANTI_AIR_TARGETTING_TO_CHANCE = 0.10 --was 0.15
NDefines.NNavy.ANTI_AIR_ATTACK_TO_AMOUNT = 0.05 --was 0.1
NDefines.NNavy.ANTI_AIR_TARGETING = 0.65 --was 0.7
NDefines.NNavy.SHIP_TO_FLEET_ANTI_AIR_RATIO = 0.4 --was 0.4
NDefines.NNavy.ANTI_AIR_POW_ON_INCOMING_AIR_DAMAGE	= 0.15 --was 0.15
NDefines.NNavy.ANTI_AIR_MULT_ON_INCOMING_AIR_DAMAGE = 0.2 --was 0.2
NDefines.NNavy.MAX_ANTI_AIR_REDUCTION_EFFECT_ON_INCOMING_AIR_DAMAGE = 0.65 --was 0.65
NDefines.NNavy.TRAINING_DAILY_COUNTRY_EXP_FACTOR = 0.0000 --was 0.0000
NDefines.NNavy.PRIDE_OF_THE_FLEET_UNASSIGN_COST = 0 --was 0
NDefines.NNavy.NAVAL_MINES_IN_REGION_MAX = 0.0 --was 0.0
NDefines.NNavy.NAVAL_MINES_PLANTING_SPEED_MULT = 0.0 --was 0.0
NDefines.NNavy.INITIAL_ALLOWED_DOCKYARD_RATIO_FOR_REPAIRS = 1.0 --was 1.0
NDefines.NNavy.CONVOY_DEFENSE_MAX_CONVOY_TO_SHIP_RATIO = 40.0 --was 40.0
NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.75 --was 0.7
NDefines.NNavy.SUPREMACY_PER_SHIP_PER_MANPOWER = 0.10 --0.10
NDefines.NNavy.SUPREMACY_PER_SHIP_PER_IC = 0.01 --was 0.01
NDefines.NNavy.SUPREMACY_PER_SHIP_BASE = 0.0 --was 0.0
NDefines.NNavy.ADMIRAL_TASKFORCE_CAP = 20 --was 10
NDefines.NNavy.MIN_HIT_PROFILE_MULT = 0.05 --was 0.0
NDefines.NNavy.CONVOY_EFFICIENCY_LOSS_MODIFIER = 0.75 --was 1.25
NDefines.NNavy.CONVOY_EFFICIENCY_REGAIN_AFTER_DAYS = 5 --was 7
NDefines.NNavy.CONVOY_EFFICIENCY_REGAIN_BASE_SPEED = 0.05 --was 0.04
NDefines.NNavy.LEADER_EXPERIENCE_SCALE = 0.0 --was 1.0
NDefines.NNavy.MISSION_FUEL_COSTS = {  -- fuel cost for each mission
		0.0, -- HOLD (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		1.0, -- PATROL		
		1.0, -- STRIKE FORCE (does not cost fuel at base, and uses IN_COMBAT_FUEL_COST in combat. this is just for the movement in between)	
		1.0, -- CONVOY RAIDING
		1.0, -- CONVOY ESCORT
		1.0, -- MINES PLANTING	
		1.0, -- MINES SWEEPING	
		0.2, -- TRAIN
		0.0, -- RESERVE_FLEET (consumes fuel HOLD_MISSION_MOVEMENT_COST fuel while moving)
		1.0, -- NAVAL_INVASION_SUPPORT (does not cost fuel at base, only costs while doing bombardment and escorting units)
	}
NDefines.NNavy.MISSION_SPREADS = {  -- mission spreads in the case a ship join combat, whih defines their starting position
		0.0, -- HOLD 
		0.0, -- PATROL		
		0.0, -- STRIKE FORCE 
		0.5, -- CONVOY RAIDING
		0.5, -- CONVOY ESCORT
		1.0, -- MINES PLANTING	
		1.0, -- MINES SWEEPING	
		0.5, -- TRAIN
		0.0, -- RESERVE_FLEET
		0.0, -- NAVAL_INVASION_SUPPORT
	}
NDefines.NNavy.MISSION_SUPREMACY_RATIOS = { -- supremacy multipliers for different mission types
		0.0, -- HOLD
		1.0, -- PATROL		
		0.0, -- STRIKE FORCE 
		0.5, -- CONVOY RAIDING
		0.5, -- CONVOY ESCORT
		0.0, -- MINES PLANTING	
		0.0, -- MINES SWEEPING	
		0.0, -- TRAIN
		0.0, -- RESERVE_FLEET
		0.0, -- NAVAL_INVASION_SUPPORT
	}
NDefines.NNavy.TRAINING_ACCIDENT_CHANCES = 0.00 --was 0.02
NDefines.NNavy.SUBMARINE_HIDE_TIMEOUT = 24 --was 20
NDefines.NNavy.SUBMARINE_REVEALED_TIMEOUT = 18 --was 16
NDefines.NNavy.SUBMARINE_REVEAL_POW = 5.0 --was 3.0
NDefines.NNavy.SUBMARINE_BASE_TORPEDO_REVEAL_CHANCE = 0.5 --was 0.035

NDefines.NAI.DIVISION_UPGRADE_MIN_XP = 400 --was 5
NDefines.NAI.DIVISION_CREATE_MIN_XP = 500 --was 100
NDefines.NAI.VARIANT_UPGRADE_MIN_XP = 500 --was 50
NDefines.NAI.PLAN_ATTACK_MIN_ORG_FACTOR_HIGH = 0.40 --was 0.2
NDefines.NAI.PLAN_ATTACK_MIN_STRENGTH_FACTOR_HIGH = 0.30 --was 0.15
NDefines.NAI.ORG_UNIT_WEAK = 0.30 --was 0.15
NDefines.NAI.STR_UNIT_WEAK = 0.40 --was 0.2
NDefines.NAI.STR_UNIT_STRONG = 0.80 --was 0.75
NDefines.NAI.AT_WAR_THREAT_FACTOR = 4.0 --was 2.0
NDefines.NAI.ATTACK_HEAVILY_DEFENDED_LIMIT = 0.9 --was 0.5
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROLLED = 0 --was 1
NDefines.NAI.GIVE_STATE_CONTROL_MIN_CONTROL_DIFF = 0 --was 2
NDefines.NAI.GIVE_STATE_CONTROL_BASE_SCORE = 1 --was 50
NDefines.NAI.MAX_VOLUNTEER_ARMY_FRACTION = 0.0001 --was 0.25
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_BASE = 100 --was 50
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_TRASHHOLD = 0 --was 20
NDefines.NAI.DIPLOMACY_ACCEPT_ATTACHE_OPINION_PENALTY = 0 --was -100